# This workflow will build the game binary

name: Build

on:
  push:
    branches: [ "feature/github-workflows" ]

permissions:
  contents: write

jobs:
  format-code:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Build game
        run: |
          scripts/buildWindows.bat
